name: hipster
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.13
  shared_preferences: ^2.0.12
  package_info: ^2.0.2
  connectivity: ^3.0.6
  cupertino_icons: ^1.0.2
  provider: ^6.1.1
  shimmer: ^2.0.0
  flutter_riverpod:
  dio: 5.1.1
  go_router: ^14.1.0
  cached_network_image: ^3.3.1
  flutter_screenutil: 5.9.0
  package_info_plus: ^5.0.1
  lucide_icons: ^0.257.0
  animations: ^2.0.0
  lottie: ^2.7.0
  device_info_plus: ^9.1.2
  flutter_animate: ^4.3.0
  flutter_slidable: ^3.0.0
  flutter_offline: ^2.0.0
  connectivity_plus: 5.0.0
  intl: any



flutter_icons:
  ios: true
  android: true
  remove_alpha_ios: true
  image_path_ios: "assets/logo/logo.png"
  image_path_android: "assets/logo/logo.png"

dependency_overrides:
  web: ^0.5.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.0.5
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
